---
title: ""
format: 
  dashboard:
    nav-buttons: [github]
    github: https://github.com/
logo: images/logo.png
theme: [sandstone, theme/custom.scss]
fig-width: 10
fig-asp: 0.3
editor_options: 
  chunk_output_type: console
---


```{r}
#| label: load-packages
#| message: false
#| context: setup
library(tidyverse)

```


# Evolução

```{r}

data <- readxl::read_excel("data/ger_energ_40_04-07-24.xlsx", sheet = "geracao_consumo")

data <- data %>% select(-tipo_geracao_hierarquia)

```

## Row {.tabset}

```{r}
#| title: Evolução
d_m <- data %>% filter(pais=="World" & Ano>=1992)
d_m2 <- d_m %>% pivot_wider(names_from="tipo_geracao", values_from="BillionkWh")
d_m2 <- d_m2 %>% rename(G_mundo="Generation", C_mundo="Consumption")


d1 <- data %>% filter(pais %in% c("China","United States","India","Russia","Japan","Brazil","Canada", "South Korea","Germany","France", "Spain", "United Kingdom") & Ano>=1992)

d2 <- d1 %>% pivot_wider(names_from="tipo_geracao", values_from="BillionkWh")

dados_j <- full_join(d2, d_m2, by="Ano")

d3 <- dados_j %>% group_by(Ano) %>% reframe(Pais=pais.x, percentualg=Generation/G_mundo*100, 
percentualc=Consumption/C_mundo*100)

d2 <- d2 %>% rename(Geração="Generation", Consumo="Consumption")

library(plotly)
library(ggplot2)
p<- d2%>%
  ggplot(aes(x=Geração, y=Consumo, color = pais,frame = Ano)) + geom_point(size=3) +
  scale_y_continuous(limits = c(0, 9000)) +  
  labs(x = "Geração de Energia Elétrica (BKWH)", 
       y = "Consumo de Energia Elétrica (BKWH)", 
       title = "Geração vs Consumo dos Top 12",
       color = "País")
  

ggplotly(p)
```


```{r}
#| title: Percentual

d4 <- d3 %>% pivot_longer(cols = starts_with("perc"), names_to = "Tipo", values_to = "Percentual") %>% arrange(Ano,desc(Percentual))

p1<- d3 %>%
  ggplot(aes(x=percentualg, y=percentualc, color = Pais,frame = Ano)) + geom_point(size=3) + 
  scale_y_continuous(limits = c(0, 50)) +
  scale_x_continuous(limits = c(0, 50)) +
  labs(x = "Geração de Energia Elétrica (%)", 
       y = "Consumo de Energia Elétrica (%)", 
       title = "Geração vs Consumo dos Top 12",
       color = "País")

ggplotly(p1)
 
 # plot_ly(x = ~Tipo, y = ~Percentual, color = ~Pais, frame=~Ano) %>%
 #  add_bars() %>% layout(barmode = "stack")
# plot_ly(x = ~Tipo, y = ~Percentual, type = "bar", color = ~Pais, frame=~Ano) |> 
#   layout(barmode = "stack")
```


# Percentual

```{r}
d4 <- d3 %>% pivot_longer(cols = starts_with("perc"), names_to = "Tipo", values_to = "Percentual") %>% arrange(Ano,desc(Percentual))
```

## Column

```{r}
p1 <- d4 %>% filter(Tipo=="percentualg" & Ano==1992) %>%  ggplot(aes(
           y = reorder(Pais,Percentual), 
           x=Percentual,
           tooltip = Percentual,
           data_id = Pais)) +
  geom_bar(stat="identity", 
                       fill="steelblue") +
  labs(y="", x="1992") + 
  theme_minimal()

ggplotly(p1)
```


```{r}
p2 <- d4 %>% filter(Tipo=="percentualg" & Ano==2002) %>%  ggplot(aes(
           y = reorder(Pais,Percentual), 
           x=Percentual,
           tooltip = Percentual,
           data_id = Pais)) +
  geom_bar(stat="identity", 
                       fill="steelblue") +
  labs(y="", x="2002") + 
  theme_minimal()
ggplotly(p2)
```

## Column

```{r}
p3 <- d4 %>% filter(Tipo=="percentualg" & Ano==2012) %>%  ggplot(aes(
           y = reorder(Pais,Percentual), 
           x=Percentual,
           tooltip = Percentual,
           data_id = Pais)) +
  geom_bar(stat="identity", 
                       fill="steelblue") +
  labs(y="", x="2012") + 
  theme_minimal()

ggplotly(p3)
```

```{r}
p4 <- d4 %>% filter(Tipo=="percentualg" & Ano==2022) %>%  ggplot(aes(
           y = reorder(Pais,Percentual), 
           x=Percentual,
           tooltip = Percentual,
           data_id = Pais)) +
  geom_bar(stat="identity", 
                       fill="steelblue") +
  labs(y="", x="2022") + 
  theme_minimal()

ggplotly(p4)
```

# BKWH

## Column

```{r}

p5<- d2%>% filter(Ano==1992) %>%  ggplot(aes(
           y = reorder(pais,Geração), 
           x=Geração,
           tooltip = Geração,
           data_id = pais)) +
  geom_bar(stat="identity", 
                       fill="steelblue") +
  labs(y="", x="1992") + 
  theme_minimal()

ggplotly(p5)
```


```{r}

p6<- d2%>% filter(Ano==2002) %>%  ggplot(aes(
           y = reorder(pais,Geração), 
           x=Geração,
           tooltip = Geração,
           data_id = pais)) +
  geom_bar(stat="identity", 
                       fill="steelblue") +
  labs(y="", x="2002") + 
  theme_minimal()

ggplotly(p6)
```

## Column

```{r}

p7<- d2%>% filter(Ano==2012) %>%  ggplot(aes(
           y = reorder(pais,Geração), 
           x=Geração,
           tooltip = Geração,
           data_id = pais)) +
  geom_bar(stat="identity", 
                       fill="steelblue") +
  labs(y="", x="2012") + 
  theme_minimal()

ggplotly(p7)
```


```{r}

p8<- d2%>% filter(Ano==2022) %>%  ggplot(aes(
           y = reorder(pais,Geração), 
           x=Geração,
           tooltip = Geração,
           data_id = pais)) +
  geom_bar(stat="identity", 
                       fill="steelblue") +
  labs(y="", x="2022") + 
  theme_minimal()

ggplotly(p8)
```

# Fonte

```{r}
data <- readxl::read_excel("data/ger_energ_40_04-07-24.xlsx", sheet = "nuc_ff_ren")

data <- data %>% select(-tipo_geracao_hierarquia)

dd1 <- data %>% filter(pais %in% c("China","United States","India","Russia","Japan","Brazil","Canada", "South Korea","Germany","France", "Spain", "United Kingdom") & Ano>=1992)
```

## Column

```{r}

pp1<- dd1%>% filter(Ano==1992) %>%  ggplot(aes(
           y = reorder(pais,BillionkWh), 
           x=BillionkWh,
          # tooltip = BKWH,
           data_id = pais,
           fill=tipo_geracao)) +
  geom_bar(stat="identity") +
  labs(y="", x="1992") + 
  theme_minimal()

ggplotly(pp1)

```


```{r}

pp2<- dd1%>% filter(Ano==2002) %>%  ggplot(aes(
           y = reorder(pais,BillionkWh), 
           x=BillionkWh,
        #   tooltip = BKWH,
           data_id = pais,
           fill=tipo_geracao)) +
  geom_bar(stat="identity") +
  labs(y="", x="2002") + 
  theme_minimal()

ggplotly(pp2)

```


## Column

```{r}

pp3<- dd1%>% filter(Ano==2012) %>%  ggplot(aes(
           y = reorder(pais,BillionkWh), 
           x=BillionkWh,
        #   tooltip = BKWH,
           data_id = pais,
           fill=tipo_geracao)) +
  geom_bar(stat="identity") +
  labs(y="", x="2012") + 
  theme_minimal()

ggplotly(pp3)

```


```{r}

pp4<- dd1%>% filter(Ano==2022) %>%  ggplot(aes(
           y = reorder(pais,BillionkWh), 
           x=BillionkWh,
        #   tooltip = BKWH,
           data_id = pais,
           fill=tipo_geracao)) +
  geom_bar(stat="identity") +
  labs(y="", x="2022") + 
  theme_minimal()

ggplotly(pp4)

```

# Renováveis


```{r}
data <- readxl::read_excel("data/ger_energ_40_04-07-24.xlsx", sheet = "hidro_nhidro")

data <- data %>% select(-tipo_geracao_hierarquia)

dd1 <- data %>% filter(pais %in% c("China","United States","India","Russia","Japan","Brazil","Canada", "South Korea","Germany","France", "Spain", "United Kingdom") & Ano>=1992)
```

## Column

```{r}

pp1<- dd1%>% filter(Ano==1992) %>%  ggplot(aes(
           y = reorder(pais,BillionkWh), 
           x=BillionkWh,
        #   tooltip = BKWH,
           data_id = pais,
           fill=tipo_geracao)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values=c("#56B4E9", "#F0E442")) +
  labs(y="", x="1992") + 
  theme_minimal()

ggplotly(pp1)

```


```{r}

pp2<- dd1%>% filter(Ano==2002) %>%  ggplot(aes(
           y = reorder(pais,BillionkWh), 
           x=BillionkWh,
        #   tooltip = BKWH,
           data_id = pais,
           fill=tipo_geracao)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values=c("#56B4E9", "#F0E442")) +
  labs(y="", x="2002") + 
  theme_minimal()

ggplotly(pp2)

```


## Column

```{r}

pp3<- dd1%>% filter(Ano==2012) %>%  ggplot(aes(
           y = reorder(pais,BillionkWh), 
           x=BillionkWh,
        #   tooltip = BKWH,
           data_id = pais,
           fill=tipo_geracao)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values=c("#56B4E9", "#F0E442")) +
  labs(y="", x="2012") + 
  theme_minimal()

ggplotly(pp3)

```


```{r}

pp4<- dd1%>% filter(Ano==2022) %>%  ggplot(aes(
           y = reorder(pais,BillionkWh), 
           x=BillionkWh,
        #   tooltip = BKWH,
           data_id = pais,
           fill=tipo_geracao)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values=c("#56B4E9", "#F0E442")) +
  labs(y="", x="2022") + 
  theme_minimal()

ggplotly(pp4)

```


# Solar e outras


```{r}
data <- readxl::read_excel("data/ger_energ_40_04-07-24.xlsx", sheet = "nhidro")

data <- data %>% select(-tipo_geracao_hierarquia)

dd1 <- data %>% filter(pais %in% c("China","United States","India","Russia","Japan","Brazil","Canada", "South Korea","Germany","France", "Spain", "United Kingdom") & Ano>=1992)
```

## Column

```{r}
#|title: Barras
pp1<- dd1%>% filter(Ano==1992) %>%  ggplot(aes(
           y = reorder(pais,BillionkWh), 
           x=BillionkWh,
        #   tooltip = BKWH,
           data_id = pais,
           fill=tipo_geracao)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values=c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2")) +
  labs(y="", x="1992") + 
  theme_minimal()

ggplotly(pp1)

```



```{r}

pp2<- dd1%>% filter(Ano==2002) %>%  ggplot(aes(
           y = reorder(pais,BillionkWh), 
           x=BillionkWh,
        #   tooltip = BKWH,
           data_id = pais,
           fill=tipo_geracao)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values=c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2")) +
  labs(y="", x="2002") + 
  theme_minimal()

ggplotly(pp2)

```


## Column

```{r}

pp3<- dd1%>% filter(Ano==2012) %>%  ggplot(aes(
           y = reorder(pais,BillionkWh), 
           x=BillionkWh,
        #   tooltip = BKWH,
           data_id = pais,
           fill=tipo_geracao)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values=c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2")) +
  labs(y="", x="2012") + 
  theme_minimal()

ggplotly(pp3)

```


```{r}

pp4<- dd1%>% filter(Ano==2022) %>%  ggplot(aes(
           y = reorder(pais,BillionkWh), 
           x=BillionkWh,
        #   tooltip = BKWH,
           data_id = pais,
           fill=tipo_geracao)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values=c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2")) +
  labs(y="", x="2022") + 
  theme_minimal()

ggplotly(pp4)

```

# Solar e outras 2

```{r}
#| title: Linhas
pp4<- dd1%>% ggplot(aes(
           y = BillionkWh, 
           x=Ano,
        #   tooltip = BKWH,
           data_id = pais,
           color=tipo_geracao)) +
  geom_line()  + 
  facet_wrap(~pais) +
  theme_minimal()

ggplotly(pp4)

```

# Dinâmico

```{r}

data <- readxl::read_excel("data/ger_energ_40_04-07-24.xlsx", sheet = "geracao_consumo")

data <- data %>% select(-tipo_geracao_hierarquia)

```

## Row {.tabset}

```{r}
#| title: Evolução do Consumo
d1 <- data %>% filter(pais %in% c("China","United States","India","Russia","Japan","Brazil","Canada", "South Korea","Germany","France", "Spain", "United Kingdom") & Ano>=1992)

d2 <- d1 %>% pivot_wider(names_from="tipo_geracao", values_from="BillionkWh")

d2 <- d2 %>% rename(Geração="Generation", Consumo="Consumption")

library(ddplot)

d2 %>%
  barChartRace(
    x = "Consumo",
    y = "pais",
    time = "Ano",
    ytitle = "Pais",
    xtitle = "Consumo (em Bilhões de kWh)",
    title = ""
  )
```


```{r}
#| title: Evolução da Geração
d1 <- data %>% filter(pais %in% c("China","United States","India","Russia","Japan","Brazil","Canada", "South Korea","Germany","France", "Spain", "United Kingdom") & Ano>=1992)

d2 <- d1 %>% pivot_wider(names_from="tipo_geracao", values_from="BillionkWh")

d2 <- d2 %>% rename(Geração="Generation", Consumo="Consumption")

library(ddplot)

d2 %>%
  barChartRace(
    x = "Geração",
    y = "pais",
    time = "Ano",
    ytitle = "Pais",
    xtitle = "Geração (em Bilhões de kWh)",
    title = ""
  )
```

